#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source /home/josh/.local/bin/virtualenvwrapper.sh
source /home/josh/kenova/kenova
bindkey -e

export TERM="xterm-256color"
export WORKON_HOME=~/Envs
export EDITOR=vim
export XDG_CONFIG_HOME=~/.config


alias ll='ls -l --color=auto'
alias -s odt=libreoffice
alias vpn='sudo openconnect -b -u josh5700 https://vpn1.dfw1.rackspace.com --script /etc/vpnc/vpnc-script'
alias shutdown='sudo systemctl poweroff'

function apep { autopep8 "$1" -r -v -i -p 2000; }

#Powerline shell
function powerline_precmd() {
  export PS1="$(~/powerline-shell.py $? --shell zsh)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
if [ "$s" = "powerline_precmd" ]; then
return
fi
done
precmd_functions+=(powerline_precmd)
}

install_powerline_precmd

